
-- Productes

INSERT INTO public.productes VALUES (1, 'AIR FORCE 1 ''07', 'nike', 'home', 120.99, 'Les Nike Air Force 1''07, un model original de bàsquet que introdueix un nou gir als seus ja característics revestiments amb costures duradores, els seus acabats impecables i la quantitat perfecta de reflector.', 'sneaker', '/img/productes/home/AIR_FORCE_1_07/AIR-FORCE-1-07-WHITE-00.webp');
INSERT INTO public.productes VALUES (2, 'AIR JORDAN 1', 'jordan', 'home', 129.99, 'Gaudeix d''un look amb estil i sempre a la moda. Les Air Jordan 1 Low us ofereixen una part de la història i el llegat Jordan amb una comoditat que dura tot el dia. Trieu els colors i surt al carrer amb l''icònic perfil dissenyat amb una combinació de materials d''alta qualitat i una unitat Air encapsulada al taló.', 'sneaker', '/img/productes/home/AIR_JORDAN_1/AIR-JORDAN-1-WHITE-00.webp');
INSERT INTO public.productes VALUES (3, 'EVA RUNNER LACEUP', 'calvin klein', 'home', 89.95, 'Sabatilles esportives de la marca Calvin Klein amb un acabat amb tela.', 'sneaker', '/img/productes/home/EVA_RUNNER_LACEUP/EVA-RUNNER-LACEUP-WHITE-00.webp');
INSERT INTO public.productes VALUES (4, 'CAVEN 2.0', 'puma', 'dona', 70, 'Les Caven 2.0 són una versió subtil d''un model de bàsquet dels anys 80 que crea un clàssic fidel a l''original tant dins com fora de la pista. Aquestes sabatilles, que combinen l''escuma SoftFoam increïblement còmoda amb una moderna estètica retro, són l''essència de l''estil esportiu.', 'sneaker', '/img/productes/dona/CAVEN_2.0/CAVEN-2.0-WHITE-00.webp');
INSERT INTO public.productes VALUES (5, 'FORUM BOLD', 'adidas', 'dona', 109.99, 'Dóna curs al teu estil amb aquesta sabatilla adidas Forum Bold Stripes. Aquesta versió de la Forum de 1984 conserva tots els detalls i materials del model original. Els trèvols de grans dimensions li aporten un toc divertit, mentre que l''aire exagerat de la sola de goma amb plataforma et permet destacar entre la multitud.', 'sneaker', 'img/productes/dona/FORUM_BOLD/FORUM-BOLD-WHITE-00.webp');
INSERT INTO public.productes VALUES (6, 'ZIANE PLATFORM', 'lacoste', 'dona', 109.99, 'Esportiu de la marca Lacoste en color blanc. Tall de pell i sintètic. Folre tèxtil. Tancament de cordons gruixuts. Sola vulcanitzada amb goma amb plataforma de 3 cm', 'sneaker', '/img/productes/dona/ZIANE_PLATFORM/ZIANE-PLATFORM-WHITE-00.webp');
INSERT INTO public.productes VALUES (7, 'COURT BOROUGH RECRAFT', 'nike', 'nens', 59.99, 'Feta per durar, aquesta llegenda redissenyada utilitza una combinació de materials reciclats a la part superior i la sola exterior per aconseguir un look clàssic renovat. La puntera i el migpeu redissenyats ofereixen espai addicional als peus per córrer, saltar i jugar més temps.', 'sneaker', '/img/productes/nens/COURT_BOROUGH_RECRAFT/COURT-BOROUGH-RECRAFT-WHITE-00.webp');
INSERT INTO public.productes VALUES (8, 'FORUM', 'adidas', 'nens', 84.95, 'La sneaker FORUM de adidas es perfecte per els més petits de la casa.', 'sneaker', '/img/productes/nens/FORUM/FORUM-WHITE-00.webp');
INSERT INTO public.productes VALUES (9, 'NEW UNION K', 'levi''s', 'nens', 50, 'Les NEW UNION K de LEVIS són unes sneakers fetes de pòliester i tela.', 'sneaker', '/img/productes/nens/NEW_UNION_K/NEW-UNION-K-WHITE-00.webp');